FROM archlinux:latest

RUN pacman --sync --sysupgrade --refresh --refresh --noconfirm \
    clang \
    meson \
    pkgconf \
    sdl3

RUN useradd --create-home builder

ENV USER=builder
ENV HOME=/home/builder

ENV CC="clang"
ENV CXX="clang++"
ENV CFLAGS="-g -fsanitize=address"
ENV CXXFLAGS="-g -fsanitize=address"
ENV LDFLAGS="-fsanitize=address -fopenmp=libgomp"

USER builder
